resource "local_file" "pet" {
    filename = var.filename
    content = "My favourite pet is ${random_pet.my-pet.id}"
}

resource "random_pet" "my-pet" {
    prefix = var.prefix
    length = var.length
    separator = var.separator
}

output "pet-name" {
    value = random_pet.my-pet.id
    description = "Records the value of the pet ID generated by the random_pet resource."
}